apiVersion: v2
name: otel-add-on
description: A Helm chart for otel-add-on
type: application
version: v0.0.0-0
appVersion: v0.0.0-0
kubeVersion: ">= 1.19.0-0"
icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png

dependencies:
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.107.0
    condition: opentelemetry-collector.enabled

home: https://github.com/kedify/otel-add-on
sources:
  - https://github.com/kedify/otel-add-on
  - https://github.com/open-telemetry/opentelemetry-helm-charts
