# https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
ui:
  message: "Hello OTEL+KEDA"
  color: "#222222"
  logo: "https://kedify.io/assets/images/logo.svg"

service:
  type: "NodePort"
  nodePort: 31198

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "9797"
  prometheus.io/scheme: "http"

#ingress:
#  enabled: true
