# https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
ui:
  message: "Hello OTEL+KEDA"
  color: "#222222"
  logo: "https://kedify.io/assets/images/logo.svg"

service:
  type: "NodePort"
  nodePort: 31198
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9898"
#ingress:
#  enabled: true
