apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dapr.io/enable-metrics: "true"
    dapr.io/metrics-port: "9090"
    dapr.io/metrics-push-enable: "true"
    dapr.io/metrics-push-endpoint: otelcol:55678
  labels:
    app: node
  name: nodeapp
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dapr.io/app-id: nodeapp
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
        dapr.io/enabled: "true"
        dapr.io/metrics-push-enable: "true"
        dapr.io/metrics-push-endpoint: otelcol:55678
      creationTimestamp: null
      labels:
        app: node
    spec:
      containers:
        - env:
            - name: APP_PORT
              value: "3000"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: otelcol:55678
          image: ghcr.io/dapr/samples/hello-k8s-node:latest
          imagePullPolicy: Always
          name: node
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
