apiVersion: v1
kind: Service
metadata:
  name: keda-otel-scaler
  labels:
    {{- include "otel-add-on.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.otlpReceiverPort }}
      targetPort: {{ .Values.service.otlpReceiverPort }}
      protocol: TCP
      name: grpc-otlp-receiver
    - port: {{ .Values.service.otlpReceiverPort }}
      targetPort: {{ .Values.service.kedaExternalScalerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "otel-add-on.selectorLabels" . | nindent 4 }}
