# helm upgrade -i keda-otel helmchart/otel-add-on/ --set image.repository=docker.io/jkremser/otel-add-on --set image.tag=latest

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: otel-example
spec:
  scaleTargetRef:
    name: nodeapp
  triggers:
    - type: external
      metadata:
        scalerAddress: keda-otel-scaler:4318

        # required
        metricQuery: "sum(http/server/request_count{app_id=nodeapp, method=GET, path=/v1.0/state/statestore})"

        # optional - default no limit
        clampMin: 1

        # optional - default no limit
        clampMax: 10

        # optional - default 'last_one', available values: last_one,rate,count,avg,min,max
        operationOverTime: last_one
