apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
   name: nodeapp-service-resiliency
   namespace: default
scopes: [pythonapp]
spec:
   policies:
      timeouts:
        short: 30s
      retries:
        retryForever:
          policy: constant
          duration: 0.5s
          maxRetries: 180
   targets:
      apps:
        nodeapp:
          retry: retryForever
          timeout: short
