definitions:
  rest.MetricDataPayload:
    properties:
      aggregatesOverTime:
        additionalProperties:
          type: number
        type: object
      data:
        items:
          $ref: '#/definitions/types.ObservedValue'
        type: array
      labels:
        $ref: '#/definitions/types.Labels'
      lastUpdate:
        type: integer
    type: object
  rest.OperationResult:
    properties:
      error:
        type: string
      ok:
        type: boolean
      operation:
        type: string
      value:
        type: number
    type: object
  rest.QueryRequest:
    properties:
      operationOverTime:
        example: rate
        type: string
      query:
        example: avg(runtime_service_invocation_req_recv_total{app_id=nodeapp,src_app_id=pythonapp})
        type: string
    type: object
  types.Labels:
    additionalProperties: {}
    type: object
  types.ObservedValue:
    properties:
      time:
        description: timestamp of last update (in seconds)
        type: integer
      value:
        description: observed value
        type: number
    type: object
info:
  contact: {}
paths:
  /info:
    get:
      consumes:
      - application/json
      description: this will return versions, ports, ...
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: get basic info about the app
      tags:
      - info
  /memstore/data:
    get:
      consumes:
      - application/json
      description: this will return detailed metrics, including all the datapoints
        and calculated aggregates
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/rest.MetricDataPayload'
              type: array
            type: object
      summary: get metrics dump
      tags:
      - metrics
  /memstore/names:
    get:
      consumes:
      - application/json
      description: this will return the metric names of all tracked metric series
        in the store
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: get metric names in the store
      tags:
      - metrics
  /memstore/query:
    post:
      consumes:
      - application/json
      description: evaluates provided query on top of internal metric storage
      parameters:
      - description: QueryRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.QueryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.OperationResult'
        "500":
          description: Internal Server Error
      summary: queries the metric storage
      tags:
      - metrics
  /memstore/reset:
    post:
      consumes:
      - application/json
      description: deletes all the data in the internal metric store
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.OperationResult'
      summary: resets mem storage
      tags:
      - ops
swagger: "2.0"
