name: 'Release the thing'

on:
  push:
    tags:
      - 'v*.*.*-*'

jobs:
  build-and-publish-images:
    secrets: inherit
    uses: kedify/github-meta/.github/workflows/kedify-release.yml@main
    with:
      tag: ${{ github.ref_name }}
