name: 'Release the thing'

on:
  push:
    tags:
      - 'v*.*.*-*'

jobs:
  build-and-publish-images:
    secrets: inherit
    uses: kedify/github-meta/.github/workflows/kedify-release.yml@main
    with:
      tag: ${{ github.ref_name }}

  post-release-work:
    runs-on: ubuntu-latest
    needs: [ build-and-publish-images ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: yq
        uses: mikefarah/yq@3.3.0
      - name: Compare versions
        id: version
        run: |
          latest_version=$(make version)
          maybe_old_version=$(yq '.version' helmchart/otel-add-on/Chart.yaml)
          echo "latest_version: ${latest_version}"
          echo "maybe_old_version: ${maybe_old_version}"
          if [ "${latest_version}" != "${maybe_old_version}" ]; then
            echo "modifying Chart.yaml.."
            yq -i ".version=\"${latest_version}\" | .appVersion=\"${latest_version}\"" helmchart/otel-add-on/Chart.yaml
            echo "newVersion=${latest_version}" >> ${GITHUB_OUTPUT}
            echo "oldVersion=${maybe_old_version}" >> ${GITHUB_OUTPUT}
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@b4d51739f96fca8047ad065eccef63442d8e99f7 # tag=v4
        id: cpr
        with:
          title: "Update chart.yaml"
          branch: chart-yaml-update
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "[post-release] Updating Chart.yaml: ${{ steps.version.outputs.oldVersion }} -> ${{ steps.version.outputs.newVersion }}"
          delete-branch: true
          base: main
          signoff: true
          body: |
            :package: Chart.yaml update :package:
            ### automated change
            Updating Chart.yaml: ${{ steps.version.outputs.oldVersion }} -> ${{ steps.version.outputs.newVersion }}
            This automated PR was created by [this action](https://github.com/kedify/otel-add-on/actions/runs/${{ github.run_id }}).

      - name: Check PR
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}" | tee -a "$GITHUB_STEP_SUMMARY"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}" | tee -a "$GITHUB_STEP_SUMMARY"
